{% set name = "xdg" %}
{% set version = "6.0.2" %}
{% set sha256 = "950504e14d27cf3c9cb37744680a43bf0ac42efefc4ef4acf98dc736cab2bced" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/x/xdg-base-dirs/xdg_base_dirs-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - xdg
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/srstevenson/xdg-base-dirs
  license: ISC
  license_file: LICENCE
  summary: Variables defined by the XDG Base Directory Specification

  description: |
    xdg is a tiny Python module which provides the variables defined by the XDG Base Directory Specification, to save you from
    duplicating the same snippet of logic in every Python utility you write that deals with user cache, configuration, or data files.

extra:
  recipe-maintainers:
    - kain88-de
    - ytausch
